### ISSUE TITLE
markdown parsing fails for links with scheme in their text segment

### ISSUE THREAD

**Issue by pi0** [nuxt/content#737]
### Version
@nuxt/content: ^1.11.1
nuxt: 2.14.12

### Reproduction Link

- https://5ewod.sse.codesandbox.io/
- https://codesandbox.io/s/5ewod?file=/content/en/index.md

Related issue: https://github.com/nuxt/nuxtjs.org/pull/1194

### What is Expected?

Markdown parsing works for links that their title is starting with an scheme (`http://`)

### What is actually happening?

Parsing does not happens for markdown style links

**Comment by AlexanderBelokon** [comment]
Hey! I've looked at this issue, and it's a bug in [micromark-extension-gfm-autolink-literal](https://github.com/micromark/micromark-extension-gfm-autolink-literal), there's even an unfinished [pull request](https://github.com/micromark/micromark-extension-gfm-autolink-literal/pull/6) to fix it. According to @ChristianMurphy's [comment](https://github.com/remarkjs/remark-gfm/issues/6#issuecomment-767775803), pinning it at 0.5.4 or 0.5.3 should fix this problem

**Comment by AlexanderBelokon** [comment]
I've confirmed pinning micromark-extension-gfm-autolink-literal@0.5.4 fixes this issue with the following addition to package.json:
```
  "resolutions": {
    "*/**/micromark-extension-gfm-autolink-literal": "0.5.4"
  }
```
but this is yarn-specific. Should I submit a pull request with this fix, or is there a better, universal way to do this?

**Comment by pi0** [comment]
[sandbox](https://codesandbox.io/s/5ewod?file=/content/en/index.md) recreated to use latest version of micromark-extension-gfm-autolink-literal (0.5.6) with fix. I have another issue now `/en/index`. Trying to investigate...

**Comment by pi0** [comment]
For some reason sandbox still broken but working fine locally so issue is resolved by dep
